#!/bin/bash

# Enable mozilla headless mode
# https://intoli.com/blog/running-selenium-with-headless-firefox/
# export MOZ_HEADLESS='1'

if [ ! `command -v inotifywait` ]; then
    echo "ERROR: 'inotify-tools' is not installed!"
    exit 1
fi

$@

while true; do
    OUTPUT=$(inotifywait --quiet --recursive --event modify --exclude '(\.swp|\.git)' .)
    clear
    echo `date`
    echo $OUTPUT
    $@
done

